version: "3.3"
services:
  hackstack_portal_backend:
    image: hackstack_portal_backend
    container_name: hackstack_portal_backend
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"

    ports:
      - "6034:5000"
    env_file:
      - .env
    networks:
      - backend_welfare-board-strapi


networks:
  backend_welfare-board-strapi:
    external: true